name: thunderbird
version: 59.0b1
summary: Mozilla Thunderbird email application
description: Thunderbird is a free email application that’s easy to set up and customize - and it’s loaded with great features!
confinement: strict
grade: stable

apps:
  thunderbird:
    command: desktop-launch $SNAP/thunderbird-bin
    environment:
      DISABLE_WAYLAND: 1
    plugs:
      - avahi-observe
      - browser-sandbox
      - camera
      - cups-control
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - network
      - network-control
      - opengl
      - pulseaudio
      - unity7
      - x11

plugs:
  browser-sandbox:
    interface: browser-support
    allow-sandbox: true

parts:
  thunderbird:
    plugin: dump
    source: https://archive.mozilla.org/pub/thunderbird/releases/59.0b1/linux-x86_64/en-US/thunderbird-59.0b1.tar.bz2
    stage-packages:
      - libxt6
      - libdbus-glib-1-2
      - libasound2
      - libpulse0
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libmirclient9
      - desktop-file-utils
    organize:
      "snap/thunderbird/current/usr/*": usr/lib/thunderbird
    after: [desktop-gtk3]
  magic:
    after: [thunderbird]
    plugin: nil
    stage-packages:
      - libglib2.0-0
      - libglib2.0-bin
      - shared-mime-info
      - gtk-update-icon-cache
    install: |
      set -eux
      glib-compile-schemas $SNAPCRAFT_PART_INSTALL/usr/share/glib-2.0/schemas
      update-mime-database $SNAPCRAFT_PART_INSTALL/usr/share/mime
      for dir in $SNAPCRAFT_PART_INSTALL/usr/share/icons/*; do
        if [ -f "$dir/index.theme" ]; then
          gtk-update-icon-cache --force "$dir"
        fi
      done
