name: thunderbird
version: 58.0b2
summary: Mozilla Thunderbird email application
description:  Thunderbird is a free email application that’s easy to set up and customize - and it’s loaded with great features!
confinement: strict

apps:
  thunderbird:
    command: desktop-launch $SNAP/thunderbird-bin
    environment:
      DISABLE_WAYLAND: 1
    plugs:
      - browser-sandbox
      - camera
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - network
      - network-control
      - opengl
      - pulseaudio
      - unity7
      - x11

plugs:
  browser-sandbox:
    interface: browser-support
    allow-sandbox: true

parts:
  thunderbird:
    plugin: dump
    source: https://archive.mozilla.org/pub/thunderbird/releases/58.0b2/linux-x86_64/en-US/thunderbird-58.0b2.tar.bz2
    stage-packages:
      - libxt6
      - libdbus-glib-1-2
      - libasound2
      - libpulse0
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libmirclient9
      - desktop-file-utils
    organize:
      "snap/thunderbird/current/usr/*": usr/lib/thunderbird
    after: [desktop-gtk3]
